"""
schemas.py — Pydantic Data Models for NexShield Data Contracts
===============================================================
Enforces strict type checking, data validation, and serialization
for scanner output, CVE data, threat engine findings, and API payloads.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, field_validator


class TargetValidation(BaseModel):
    """Result schema for scanner target validation."""
    valid: bool
    type: Optional[str] = None  # 'ipv4', 'ipv6', 'cidr', 'hostname'
    value: str
    host_count: Optional[int] = None
    is_private: Optional[bool] = None
    is_loopback: Optional[bool] = None
    error: Optional[str] = None


class HostPort(BaseModel):
    """Represents a single open/filtered network port."""
    port: int = Field(..., ge=1, le=65535, description="Port number between 1 and 65535")
    protocol: str = Field(default="tcp", description="Protocol: tcp or udp")
    state: str = Field(default="open", description="Port state: open, closed, filtered")
    service: str = Field(default="unknown", description="Service name detected on port")
    version: str = Field(default="", description="Service version string")
    banner: Optional[str] = Field(default="", description="Banner text extracted")


class ProtocolFootprint(BaseModel):
    """Represents open ports grouped under a protocol for a host."""
    protocol: str = "tcp"
    ports: List[HostPort] = Field(default_factory=list)


class ScanFootprint(BaseModel):
    """Complete network footprint returned by scanner for a target host."""
    host: str
    status: str = "complete"
    protocols: List[ProtocolFootprint] = Field(default_factory=list)
    os_name: Optional[str] = "Unknown OS"
    os_accuracy: Optional[int] = 0
    scanned_at: Optional[str] = None


class ThreatItem(BaseModel):
    """Standardized finding schema generated by AI threat engines."""
    name: str = Field(..., description="Short threat title")
    severity: str = Field(..., description="Severity level: info, low, medium, high, critical")
    host: str = Field(..., description="Target host IP or hostname")
    cve_id: Optional[str] = Field(default="", description="Associated CVE ID or synthetic threat ID")
    source: str = Field(..., description="Name of the AI analysis engine that flagged this threat")
    detail: str = Field(..., description="Detailed description and remediation advice")
    tags: List[str] = Field(default_factory=list, description="Categorization tags")
    risk_score: Optional[float] = Field(default=0.0, description="Computed risk score (0-100)")
    created_at: Optional[str] = Field(default="", description="Timestamp when flagged")

    @field_validator("severity")
    @classmethod
    def validate_severity(cls, v: str) -> str:
        valid_severities = {"info", "low", "medium", "high", "critical"}
        lowered = v.lower().strip()
        if lowered not in valid_severities:
            return "info"
        return lowered


class CVELookupResult(BaseModel):
    """Normalized CVE document representation."""
    cve_id: str
    description: str = "No description available."
    cvss_score: Optional[float] = 0.0
    severity: str = "UNKNOWN"
    published_date: Optional[str] = None
    references: List[str] = Field(default_factory=list)
    cpe_matches: List[str] = Field(default_factory=list)
    source: str = "NVD"
